### PR TITLE
Modified generate_dds_opendds_cpp function for opendds_idl

### PR DESCRIPTION
**Pull request by kuznetsovmoci**
Modified to call OpenDDS IDL compiler

### CODE REVIEW

**Comment by adamsj-ros** [comment]
Please provide a description as to why this change is needed. 
Is this change still in work? If so, then please create a "draft" PR as Adam mentioned the other day.

**Comment by kuznetsovmoci** [comment]
> Please provide a description as to why this change is needed.
> Is this change still in work? If so, then please create a "draft" PR as Adam mentioned the other day.

I have now added a comment describing it. This is complete once reviewed and approved - not a draft. Of course bug fixes during integration tests are possible in the future.

**Comment by adamsj-ros** [comment]
> This is complete once reviewed and approved

Can you give some steps to confirm it's working as expected? For example:

1. colcon buld ....
2. cd build
3. look for blah blah files

**Comment by kuznetsovmoci** [comment]
> > This is complete once reviewed and approved
> 
> Can you give some steps to confirm it's working as expected? For example:
> 
> 1. colcon buld ....
> 2. cd build
> 3. look for blah blah files

I wrote a script to test it:

#!/usr/bin/env python3

import argparse
import sys

from InitTest import generate_dds_opendds_cpp

def main(argv=sys.argv[1:]):
    print("Test1")
    return generate_dds_opendds_cpp(
        "MyPackageName",
        ["./Input1/Input2/Test.idl", "./Input1/Input2/Test1.idl"],
        "./BasePath",
        ["dir1:/opt/workspace/Python", "dir2:/opt/workspace"],
        "./Output",
        "opendds_idl"
    )



if __name__ == '__main__':
    sys.exit(main())

It generated all output files, as expected:
image

We will need to change other files before running integration test

**Comment by sonndinh** [comment]
The code looks good to me. 
BTW, I don't think we need the Python script rosidl_typesupport_opendds_cpp/rosidl_typesupport_opendds_cpp. It defines a main entry but the correct one is already defined in bin/rosidl_typesupport_opendds_cpp.

**Comment by kuznetsovmoci** [comment]
> The code looks good to me.
> BTW, I don't think we need the Python script rosidl_typesupport_opendds_cpp/rosidl_typesupport_opendds_cpp. It defines a main entry but the correct one is already defined in bin/rosidl_typesupport_opendds_cpp.

I agree. This version is from the previous conversion trial and has not implemented much, other than some checks.

**Pull request merged**
